import math        # factorial, gcd, sqrt
import itertools   # product, permutations, combinations

# Groups are represented as (elements, op) where:
#   elements — a list of values (need not be hashable)
#   op       — a callable op(a, b) returning the group product a*b
# Rings/fields use (elements, add, mul) triples.
# Permutations are dicts {1: σ(1), 2: σ(2), ...} on {1,...,n}.
# Polynomials are lists [a₀, a₁, ..., aₙ] where index = degree, all mod p.

# ============================================================
# INTERNAL HELPERS  (prefixed _ — not part of public API)
# ============================================================

def _eq(a, b):
    """Element equality — works for both hashable and unhashable types (e.g. dicts)."""
    return a == b

def _in(x, lst):
    """List-based membership check (works when elements are not hashable)."""
    return any(_eq(x, y) for y in lst)

def _dedup(lst):
    """Remove duplicate elements from a list using equality."""
    result = []
    for x in lst:
        if not _in(x, result):
            result.append(x)
    return result

def _find_identity(elements, op):
    """Return the identity element, or None if not found."""
    for e in elements:
        if all(_eq(op(e,a),a) and _eq(op(a,e),a) for a in elements):
            return e
    return None

def _find_inverse(a, elements, op, identity):
    """Return b such that op(a,b) = op(b,a) = identity, or None."""
    for b in elements:
        if _eq(op(a,b), identity) and _eq(op(b,a), identity):
            return b
    return None

def _inverses_map(elements, op, identity):
    """Return list of (a, a_inv) pairs, or None if any element has no inverse."""
    pairs = []
    for a in elements:
        inv = _find_inverse(a, elements, op, identity)
        if inv is None:
            return None
        pairs.append((a, inv))
    return pairs

def _get_inv(a, pairs):
    """Retrieve inverse of a from the (element, inverse) pairs list."""
    for x, xi in pairs:
        if _eq(x, a):
            return xi
    return None

def _is_prime(n):
    if n < 2: return False
    for i in range(2, int(math.sqrt(n)) + 1):
        if n % i == 0: return False
    return True

def _poly_trim(poly):
    p = list(poly)
    while len(p) > 1 and p[-1] == 0:
        p.pop()
    return p

def _poly_degree(poly):
    p = _poly_trim(list(poly))
    return len(p) - 1 if any(c != 0 for c in p) else -1

# ============================================================
# GROUPS
# ============================================================

# Formula: a set G with ∗ is a group iff it satisfies closure, associativity, identity, inverses
# Returns (is_group, closure, associativity, identity, inverses_exist)
def IsGroup(elements, op):
    elems   = list(elements)
    closed  = all(_in(op(a,b), elems) for a in elems for b in elems)
    assoc   = all(_eq(op(op(a,b),c), op(a,op(b,c)))
                  for a in elems for b in elems for c in elems) if len(elems) <= 20 else True
    ident   = _find_identity(elems, op)
    has_id  = ident is not None
    pairs   = _inverses_map(elems, op, ident) if has_id else None
    has_inv = pairs is not None
    return (closed and assoc and has_id and has_inv, closed, assoc, ident, has_inv)

# Returns True if the group operation is commutative: a∗b = b∗a for all a,b ∈ G
def IsAbelian(elements, op):
    elems = list(elements)
    return all(_eq(op(a,b), op(b,a)) for a in elems for b in elems)

# Formula: |G| — cardinality of the group
def GroupOrder(elements):
    return len(list(elements))

# Formula: ord(g) — smallest positive n with gⁿ = e
def ElementOrder(g, op, identity, max_n=1000):
    cur = g
    for n in range(1, max_n+1):
        if _eq(cur, identity): return n
        cur = op(cur, g)
    return 0

# Formula: ⟨g⟩ = {e, g, g², ...} — cyclic subgroup generated by g
def CyclicSubgroup(g, op, identity, max_n=1000):
    sub = [identity]; cur = g
    for _ in range(max_n):
        if _eq(cur, identity): break
        sub.append(cur); cur = op(cur, g)
    return sub

# Returns gⁿ in the group; n may be negative if inverse_pairs is provided
def GroupPower(a, n, op, identity, inverse_pairs=None):
    if n == 0: return identity
    base = a if n > 0 else _get_inv(a, inverse_pairs)
    result = identity
    for _ in range(abs(n)):
        result = op(result, base)
    return result

# Formula: Cayley table — table[i][j] = elems[i] ∗ elems[j]
def CayleyTable(elements, op):
    elems = list(elements)
    return [[op(a,b) for b in elems] for a in elems]

# Formula: ℤₙ — cyclic group of integers mod n under addition
def CyclicGroupZn(n):
    return list(range(n)), lambda a,b: (a+b)%n

# Formula: generators of G — elements g such that ⟨g⟩ = G
def Generators(elements, op, identity):
    elems = list(elements); n = len(elems)
    return [g for g in elems if len(CyclicSubgroup(g, op, identity)) == n]

# ============================================================
# SUBGROUPS AND COSETS
# ============================================================

# Formula: one-step subgroup test — H ≤ G iff ∀a,b ∈ H: ab⁻¹ ∈ H
def IsSubgroup(H, G_elements, op, identity):
    H = list(H); G = list(G_elements)
    if not H: return False
    if not all(_in(h, G) for h in H): return False
    pairs = _inverses_map(G, op, identity)
    if pairs is None: return False
    return all(_in(op(a, _get_inv(b, pairs)), H) for a in H for b in H)

# Formula: aH = {a∗h | h ∈ H} — left coset
def LeftCoset(a, H, op):
    return _dedup([op(a,h) for h in H])

# Formula: Ha = {h∗a | h ∈ H} — right coset
def RightCoset(H, a, op):
    return _dedup([op(h,a) for h in H])

# Formula: Lagrange's Theorem — |H| divides |G|, index [G:H] = |G|/|H|
def LagrangesTheorem(G_elements, H):
    g=len(list(G_elements)); h=len(list(H))
    if h==0: return None,False
    divides=g%h==0
    return (g//h if divides else None), divides

# Returns all left cosets of H in G as a list of lists
def AllLeftCosets(G_elements, H, op):
    G=list(G_elements); cosets=[]
    for g in G:
        coset=LeftCoset(g,H,op)
        if not any(set(map(str,coset))==set(map(str,c)) for c in cosets):
            cosets.append(coset)
    return cosets

# Formula: Z(G) = {z ∈ G | zg = gz for all g ∈ G} — center of G
def Center(G_elements, op):
    G=list(G_elements)
    return [z for z in G if all(_eq(op(z,g),op(g,z)) for g in G)]

# ============================================================
# NORMAL SUBGROUPS AND QUOTIENT GROUPS
# ============================================================

# Formula: N ◁ G iff gNg⁻¹ = N for all g ∈ G
def IsNormalSubgroup(H, G_elements, op, identity):
    if not IsSubgroup(H, G_elements, op, identity): return False
    G=list(G_elements); pairs=_inverses_map(G, op, identity)
    if pairs is None: return False
    for g in G:
        g_inv=_get_inv(g, pairs)
        conj=_dedup([op(op(g,h),g_inv) for h in H])
        if set(map(str,conj)) != set(map(str,H)): return False
    return True

# Formula: G/N — quotient group whose elements are the left cosets of N
def QuotientGroup(G_elements, N, op, identity):
    if not IsNormalSubgroup(N, G_elements, op, identity): return None,None
    cosets=AllLeftCosets(G_elements, N, op)
    def coset_idx(x):
        for i,c in enumerate(cosets):
            if _in(x, c): return i
        return -1
    def coset_op(i,j):
        return coset_idx(op(cosets[i][0], cosets[j][0]))
    return cosets, coset_op

# Formula: [a,b] = a⁻¹b⁻¹ab — group commutator
def Commutator(a, b, op, inverse_pairs):
    a_inv=_get_inv(a, inverse_pairs); b_inv=_get_inv(b, inverse_pairs)
    return op(op(a_inv, b_inv), op(a,b))

# Formula: [G,G] = ⟨[a,b] | a,b ∈ G⟩ — commutator (derived) subgroup
def CommutatorSubgroup(G_elements, op, identity):
    G=list(G_elements); pairs=_inverses_map(G, op, identity)
    if pairs is None: return []
    comms=[]
    for a in G:
        for b in G:
            c=Commutator(a,b,op,pairs)
            if not _in(c, comms): comms.append(c)
    # Close under the group operation
    changed=True
    while changed:
        changed=False
        for c1 in list(comms):
            for c2 in list(comms):
                prod=op(c1,c2)
                if not _in(prod, comms): comms.append(prod); changed=True
    return comms                                               # Complete [G,G]

# ============================================================
# GROUP HOMOMORPHISMS
# ============================================================

# Formula: φ: G→H is a homomorphism iff φ(ab) = φ(a)φ(b) for all a,b ∈ G
# phi is a dict mapping G-elements to H-elements
def IsHomomorphism(G_elements, H_elements, phi, G_op, H_op):
    G=list(G_elements)
    return all(_eq(phi.get(G_op(a,b)), H_op(phi.get(a), phi.get(b))) for a in G for b in G)

# Formula: ker(φ) = {g ∈ G | φ(g) = eH}
def Kernel(phi, H_identity):
    return {g for g,img in phi.items() if _eq(img, H_identity)}

# Formula: im(φ) = {φ(g) | g ∈ G}
def Image(phi):
    return set(phi.values())

# Formula: isomorphism iff bijective homomorphism
def IsIsomorphism(G_elements, H_elements, phi, G_op, H_op):
    G=list(G_elements); H=list(H_elements)
    if not IsHomomorphism(G,H,phi,G_op,H_op): return False
    if len(set(phi.values())) != len(G): return False          # Not injective
    if set(phi.values()) != set(H): return False               # Not surjective
    return True

# Formula: First Isomorphism Theorem — G/ker(φ) ≅ im(φ), |G|/|ker|=|im|
def FirstIsomorphismTheorem(G_elements, phi, G_op, H_identity):
    ker=Kernel(phi, H_identity); img=Image(phi)
    n=len(list(G_elements)); k=len(ker)
    return ker, img, n//k if k>0 and n%k==0 else None

# ============================================================
# PERMUTATION GROUPS
# ============================================================

# Permutation on {1,...,n}: dict {1:σ(1), ..., n:σ(n)}

# Formula: (σ∘τ)(i) = σ(τ(i)) — apply τ first then σ
def PermCompose(sigma, tau):
    return {i: sigma[tau[i]] for i in tau}

# Formula: identity permutation on {1,...,n}
def PermIdentity(n):
    return {i: i for i in range(1, n+1)}

# Formula: σ⁻¹ — swap keys and values
def PermInverse(sigma):
    return {v: k for k,v in sigma.items()}

# Formula: cycle decomposition — σ as product of disjoint cycles (fixed points omitted)
def CycleDecomposition(sigma):
    visited=set(); cycles=[]
    for start in sorted(sigma):
        if start in visited: continue
        cycle=[]; x=start
        while x not in visited:
            visited.add(x); cycle.append(x); x=sigma[x]
        if len(cycle)>1: cycles.append(tuple(cycle))
    return cycles

# Formula: cycle type — sorted tuple of cycle lengths (including 1-cycles for fixed points)
def CycleType(sigma):
    n=len(sigma); cycles=CycleDecomposition(sigma)
    lens=sorted([len(c) for c in cycles], reverse=True)
    total=sum(lens)
    if total<n: lens+=[1]*(n-total)
    return tuple(sorted(lens, reverse=True))

# Formula: ord(σ) = lcm of all cycle lengths
def PermOrder(sigma):
    def lcm(a,b): return abs(a*b)//math.gcd(a,b)
    cycles=CycleDecomposition(sigma)
    if not cycles: return 1
    order=1
    for c in cycles: order=lcm(order, len(c))
    return order

# Formula: sgn(σ) = (−1)^(n − number of cycles including fixed points)
def PermSign(sigma):
    n=len(sigma)
    k=len(CycleDecomposition(sigma))+(n-sum(len(c) for c in CycleDecomposition(sigma)))
    return 1 if (n-k)%2==0 else -1

def IsEvenPermutation(sigma):
    return PermSign(sigma)==1

# Formula: Sₙ — all n! permutations on {1,...,n}
def SymmetricGroup(n):
    return [{i+1:p[i] for i in range(n)} for p in itertools.permutations(range(1,n+1))]

# Formula: Aₙ — all even permutations on {1,...,n}
def AlternatingGroup(n):
    return [s for s in SymmetricGroup(n) if IsEvenPermutation(s)]

# Formula: transposition (i j) on {1,...,n}
def Transposition(n, i, j):
    s=PermIdentity(n); s[i],s[j]=j,i; return s

# Returns σ expressed as a list of transpositions (each is a pair (a,b))
def ToTranspositions(sigma):
    trans=[]
    for cycle in CycleDecomposition(sigma):
        for k in range(len(cycle)-1):
            trans.append((cycle[0], cycle[k+1]))
    return trans

# ============================================================
# RINGS
# ============================================================

# Formula: (R,+,·) is a ring iff (R,+) is an abelian group, · is associative, and · distributes over +
# Returns (is_ring, add_is_abelian_group, mul_is_assoc, distributive)
def IsRing(elements, add, mul):
    is_g,_,_,_,_ = IsGroup(elements, add)
    abelian = IsAbelian(elements, add) if is_g else False
    elems=list(elements)
    mul_assoc=all(_eq(mul(mul(a,b),c), mul(a,mul(b,c)))
                  for a in elems for b in elems for c in elems) if len(elems)<=12 else True
    distrib=True
    for a,b,c in list(itertools.product(elems,repeat=3))[:300]:
        if not _eq(mul(a,add(b,c)), add(mul(a,b),mul(a,c))):
            distrib=False; break
        if not _eq(mul(add(b,c),a), add(mul(b,a),mul(c,a))):
            distrib=False; break
    add_ok=is_g and abelian
    return (add_ok and mul_assoc and distrib, add_ok, mul_assoc, distrib)

# Returns True if multiplication is commutative
def IsCommutativeRing(elements, mul):
    elems=list(elements)
    return all(_eq(mul(a,b),mul(b,a)) for a in elems for b in elems)

# Returns the multiplicative identity (unity) of R, or None
def RingUnity(elements, mul):
    for e in elements:
        if all(_eq(mul(e,a),a) and _eq(mul(a,e),a) for a in elements):
            return e
    return None

# Formula: a ≠ 0 is a zero divisor iff ∃b≠0 with a·b=0 or b·a=0
def ZeroDivisors(elements, add, mul):
    zero=_find_identity(elements, add)
    nonzero=[a for a in elements if not _eq(a,zero)]
    return [a for a in nonzero
            if any(_eq(mul(a,b),zero) or _eq(mul(b,a),zero) for b in nonzero)]

# Formula: char(R) — smallest positive n with n·1=0; 0 if none exists
def RingCharacteristic(elements, add, unity):
    zero=_find_identity(elements,add)
    if unity is None or zero is None: return None
    cur=unity
    for n in range(1, len(list(elements))+2):
        if _eq(cur,zero): return n
        cur=add(cur, unity)
    return 0

# Returns True if R is an integral domain: commutative ring with unity and no zero divisors
def IsIntegralDomain(elements, add, mul):
    if RingUnity(elements,mul) is None: return False
    if not IsCommutativeRing(elements,mul): return False
    return len(ZeroDivisors(elements,add,mul))==0

# Formula: ℤₙ ring — integers mod n under + and ·
def RingZn(n):
    return list(range(n)), lambda a,b:(a+b)%n, lambda a,b:(a*b)%n

# ============================================================
# IDEALS
# ============================================================

# Formula: I is a left ideal iff I is an additive subgroup and r·i ∈ I for all r ∈ R, i ∈ I
def IsLeftIdeal(I, R_elements, add, mul, add_identity):
    I=list(I); R=list(R_elements)
    pairs=_inverses_map(R, add, add_identity)
    if pairs is None: return False
    if not all(_in(add(a, _get_inv(b,pairs)), I) for a in I for b in I): return False
    return all(_in(mul(r,i), I) for r in R for i in I)

# Formula: I is a right ideal iff I·R ⊆ I
def IsRightIdeal(I, R_elements, add, mul, add_identity):
    I=list(I); R=list(R_elements)
    pairs=_inverses_map(R, add, add_identity)
    if pairs is None: return False
    if not all(_in(add(a, _get_inv(b,pairs)), I) for a in I for b in I): return False
    return all(_in(mul(i,r), I) for r in R for i in I)

# Returns True if I is a two-sided ideal
def IsIdeal(I, R_elements, add, mul, add_identity):
    return (IsLeftIdeal(I,R_elements,add,mul,add_identity) and
            IsRightIdeal(I,R_elements,add,mul,add_identity))

# Formula: ⟨a⟩ = {r·a | r ∈ R} — principal ideal generated by a (commutative ring)
def PrincipalIdeal(a, R_elements, mul):
    return sorted(_dedup([mul(r,a) for r in R_elements]))

# Formula: R/I — quotient ring (elements are cosets a+I)
def QuotientRing(R_elements, I, add, mul, add_identity):
    if not IsIdeal(I,R_elements,add,mul,add_identity): return None,None,None
    R=list(R_elements); cosets=[]
    for r in R:
        coset=_dedup([add(r,i) for i in I])
        if not any(set(map(str,coset))==set(map(str,c)) for c in cosets):
            cosets.append(coset)
    def coset_idx(x):
        for i,c in enumerate(cosets):
            if _in(x,c): return i
        return -1
    return cosets, lambda i,j:coset_idx(add(cosets[i][0],cosets[j][0])), \
                   lambda i,j:coset_idx(mul(cosets[i][0],cosets[j][0]))

# Formula: I is prime iff ab ∈ I → a ∈ I or b ∈ I
def IsPrimeIdeal(I, R_elements, mul):
    I_set=list(I); R=list(R_elements)
    for a in R:
        for b in R:
            if _in(mul(a,b),I_set) and not _in(a,I_set) and not _in(b,I_set):
                return False
    return True

# Formula: I is maximal iff R/I is a field (no proper ideals between I and R)
def IsMaximalIdeal(I, R_elements, add, mul, add_identity):
    cosets,add_op,mul_op=QuotientRing(R_elements,I,add,mul,add_identity)
    if cosets is None: return False
    n=len(cosets); zero_idx=next((i for i,c in enumerate(cosets) if _in(add_identity,c)),None)
    nonzero=[i for i in range(n) if i!=zero_idx]
    return all(mul_op(a,b)!=zero_idx for a in nonzero for b in nonzero)

# ============================================================
# FIELDS
# ============================================================

# Formula: (F,+,·) is a field iff it is a commutative ring with unity where every nonzero element
# has a multiplicative inverse
def IsField(elements, add, mul):
    is_r,add_ok,mul_assoc,distrib=IsRing(elements,add,mul)
    comm=IsCommutativeRing(elements,mul) if is_r else False
    unity=RingUnity(elements,mul); has_u=unity is not None
    zero=_find_identity(elements,add); nonzero=[a for a in elements if not _eq(a,zero)]
    all_inv=has_u and all(any(_eq(mul(a,b),unity) for b in nonzero) for a in nonzero)
    return (is_r and comm and has_u and all_inv, is_r, comm, has_u, all_inv)

# Formula: 𝔽ₚ — integers mod p under + and · (p must be prime)
def PrimeField(p):
    if not _is_prime(p): raise ValueError(f'{p} is not prime')
    return list(range(p)), lambda a,b:(a+b)%p, lambda a,b:(a*b)%p

# Formula: a⁻¹ mod p via Fermat's little theorem: a^(p-2) mod p
def FieldInverse(a, p):
    if a%p==0: return None
    return pow(int(a), p-2, p)

# Formula: char(F) — characteristic of the field
def FieldCharacteristic(elements, add, mul):
    return RingCharacteristic(elements, add, RingUnity(elements,mul))

# Returns the prime subfield generated by the unity element
def PrimeSubfield(elements, add, mul):
    unity=RingUnity(elements,mul)
    if unity is None: return []
    zero=_find_identity(elements,add); sub=[zero]; cur=unity
    while not _in(cur,sub): sub.append(cur); cur=add(cur,unity)
    return sorted(sub)

# ============================================================
# POLYNOMIAL RINGS MOD p
# ============================================================

# Polynomials over 𝔽ₚ: list [a₀,a₁,...,aₙ] where aᵢ is coefficient of xⁱ, all mod p

# Formula: (f+g) mod p
def PolyAdd(f, g, p):
    n=max(len(f),len(g)); r=[0]*n
    for i in range(len(f)): r[i]=(r[i]+f[i])%p
    for i in range(len(g)): r[i]=(r[i]+g[i])%p
    return _poly_trim(r)

# Formula: (f·g) mod p
def PolyMul(f, g, p):
    r=[0]*(len(f)+len(g)-1)
    for i,a in enumerate(f):
        for j,b in enumerate(g):
            r[i+j]=(r[i+j]+a*b)%p
    return _poly_trim(r)

# Formula: polynomial division f = q·g + r over 𝔽ₚ
# Returns (quotient, remainder)
def PolyDivMod(f, g, p):
    f=_poly_trim(list(f)); g=_poly_trim(list(g))
    if all(c==0 for c in g): raise ValueError('Division by zero polynomial')
    deg_g=_poly_degree(g); r=list(f); q=[0]*max(1, len(f))
    for i in range(len(f)-deg_g-1, -1, -1):
        if _poly_degree(r)<deg_g: break
        dr=_poly_degree(r)
        if dr<0: break
        coef=(r[dr]*FieldInverse(g[deg_g],p))%p
        q[dr-deg_g]=coef
        for j in range(deg_g+1):
            r[dr-deg_g+j]=(r[dr-deg_g+j]-coef*g[j])%p
    return _poly_trim(q), _poly_trim(r)

# Formula: gcd(f,g) in 𝔽ₚ[x] via Euclidean algorithm — returns monic GCD
def PolyGCD(f, g, p):
    f,g=list(f),list(g)
    while any(c!=0 for c in g):
        _,r=PolyDivMod(f,g,p); f,g=g,r
    f=_poly_trim(f)
    if f and f[-1]!=0:
        inv=FieldInverse(f[-1],p)
        f=[(c*inv)%p for c in f]
    return _poly_trim(f)

# Returns f(a) mod p
def PolyEval(f, a, p):
    return sum(f[i]*pow(int(a),i,p) for i in range(len(f)))%p

# Returns all roots of f in 𝔽ₚ
def PolyRoots(f, p):
    return [a for a in range(p) if PolyEval(f,a,p)==0]

# Formula: f is irreducible over 𝔽ₚ iff deg≥1 and f has no proper monic divisor
def IsIrreducible(f, p):
    f=_poly_trim(list(f)); deg=_poly_degree(f)
    if deg<=0: return False
    if deg==1: return True
    for a in range(p):                                         # Check for roots
        if PolyEval(f,a,p)==0: return False
    # Check all monic polynomials of degree 1..deg//2 for divisibility
    for d in range(2, deg//2+1):
        for coeffs in itertools.product(range(p), repeat=d):
            test=_poly_trim(list(coeffs)+[1])
            if _poly_degree(test)==d:
                _,r=PolyDivMod(f,test,p)
                if all(c==0 for c in r): return False          # Factor found
    return True

# Formula: (f·g) mod h mod p — multiplication in 𝔽ₚ[x]/⟨h⟩
def PolyMulMod(f, g, h, p):
    _,r=PolyDivMod(PolyMul(f,g,p), h, p); return r

# ============================================================
# GROUP ACTIONS
# ============================================================

# Formula: Orb(x) = {g·x | g ∈ G} — orbit of x
def Orbit(x, G_elements, action):
    return _dedup([action(g,x) for g in G_elements])

# Formula: Stab(x) = {g ∈ G | g·x = x} — stabilizer of x
def Stabilizer(x, G_elements, action):
    return [g for g in G_elements if _eq(action(g,x), x)]

# Formula: |Orb(x)| · |Stab(x)| = |G| — Orbit-Stabilizer Theorem
def OrbitStabilizerTheorem(x, G_elements, action):
    G=list(G_elements)
    orb=len(Orbit(x,G,action)); stab=len(Stabilizer(x,G,action))
    return orb, stab, orb*stab, len(G)

# Returns the partition of X into disjoint orbits
def AllOrbits(X, G_elements, action):
    X=list(X); G=list(G_elements); seen=[]; orbits=[]
    for x in X:
        if _in(x,seen): continue
        orb=Orbit(x,G,action)
        orbits.append(orb)
        for y in orb:
            if not _in(y,seen): seen.append(y)
    return orbits

# Formula: Burnside's Lemma — |X/G| = (1/|G|) Σ_{g∈G} |Fix(g)|
# Returns (number_of_orbits, {str(g): fix_count})
def BurnsideLemma(X, G_elements, action):
    G=list(G_elements); X_list=list(X)
    fixes={str(g): sum(1 for x in X_list if _eq(action(g,x),x)) for g in G}
    total=sum(fixes.values())
    return total//len(G) if total%len(G)==0 else total/len(G), fixes

# Formula: Cl(g) = {hgh⁻¹ | h ∈ G} — conjugacy class of g
def ConjugacyClass(g, G_elements, op, inverse_pairs):
    return _dedup([op(op(h,g), _get_inv(h,inverse_pairs)) for h in G_elements])

# Returns all conjugacy classes of G as a list of lists
def AllConjugacyClasses(G_elements, op, identity):
    G=list(G_elements); pairs=_inverses_map(G, op, identity)
    if pairs is None: return []
    seen=[]; classes=[]
    for g in G:
        if _in(g,seen): continue
        cls=ConjugacyClass(g, G, op, pairs)
        classes.append(cls)
        for x in cls:
            if not _in(x,seen): seen.append(x)
    return classes

# Formula: class equation — |G| = |Z(G)| + Σ [G:C_G(xᵢ)] for non-central xᵢ
# Returns (|G|, |Z(G)|, list_of_class_sizes)
def ClassEquation(G_elements, op, identity):
    G=list(G_elements)
    classes=AllConjugacyClasses(G, op, identity)
    # Elements in the center have singleton conjugacy classes
    center=[g for g in G
            if any(len(cls)==1 and _in(g,cls) for cls in classes)]
    sizes=[len(c) for c in classes]
    return len(G), len(center), sizes                          # Complete class equation

# Formula: Sylow p-subgroups — all subgroups of G of order p^k (brute force, small groups)
def SylowSubgroups(G_elements, p, k, op, identity):
    order=p**k; G=list(G_elements); result=[]
    for subset in itertools.combinations(G, order):
        S=list(subset)
        if _in(identity,S) and IsSubgroup(S,G,op,identity):
            if not any(set(map(str,S))==set(map(str,r)) for r in result):
                result.append(S)
    return result
